const Constant = {
  API_ADDRESS: "http://185.204.197.95:5000/",
  TABLE_PAGE_SIZE: 10,
  EMPLOYEE_CONTACRT: [
    { value: "HOURLY", label: "ساعتی" },
    { value: "DAYLI", label: "روزانه" },
    { value: "MONTHLY", label: "ماهانه" },
  ],
  UNITS_MAP: {
    KILOGRAM: "کیلوگرم",
    GRAM: "گرم",
    TON: "تن",
    BOX: "بکس",
    SHEL: "شل",
    CUBICMETERS: "مترمکعب",
  },
  ACTION_TYPES: {
    SHOW_ALERT: "SHOW_ALERT",
    HIDE_ALERT: "HIDE_ALERT",
    SHOW_DIALOG: "SHOW_DIALOG",
    HIDE_DIALOG: "HIDE_DIALOG",
    LOG_IN_USER: "LOG_IN_USER",
    LOG_OUT_USER: "LOG_OUT_USER",
    GET_UNITS: "GET_UNITS",
  },
  PERSON_TYPE: {
    EMPLOYEE: "employee",
    CUSTOMER: "customer",
    USER: "user",
    DRIVER: "driver",
  },
  STORAGE: {
    CURRENT_USER: "CURRENT_USER",
    TOKEN: "TOKEN",
    MODE: "MODE",
    CURRENT_LINK: "CURRENT_LINK",
    PRODUCT_UNITS: "PRODUCT_UNITS",
  },
  VALIDATION: {
    REQUIRED: "این فیلد الزامی است",
    MOBILE_NUMBER: "موبایل باید 11 عدد داشته باشد",
    PASSWORD: "رمز عبور باید حداقل 5 حرف یا رقم باشد",
    CARD_NUMBER: "شماره کارت باید 16 رقم باشد",
    POSITIVE_NUMBER: "این عدد باید مثبت باشد",
  },
  MESSAGES: {},
  ERROR_MESSAGE: {
    BAD_CREDENTIAL: "نام کاربری یا رمز عبور اشتباه است",
  },
  PERSON_STATUS: {
    DEBTOR: "بدهکار",
    NODEBT: "بستانکار",
    CREDITOR: "طلبکار",
  },
  PAYMENT_TYPE: {
    INCOME: "دریافتی",
    OUTCOME: "پرداختی",
    ALL: "دریافتی و پرداختی",
  },
  INVOICE_TYPE: {
    SELL: "فروش",
    BUY: "خرید",
  },

  ALL_PERMISSIONS: {
    USER_SHOW: "USER_SHOW",
    USER_EDIT: "USER_EDIT",
    CUSTOMER_SHOW: "CUSTOMER_SHOW",
    CUSTOMER_EDIT: "CUSTOMER_EDIT",
    DRIVER_SHOW: "DRIVER_SHOW",
    DRIVER_EDIT: "DRIVER_EDIT",
    PRODUCT_SHOW: "PRODUCT_SHOW",
    PRODUCT_EDIT: "PRODUCT_EDIT",
    DEPOT_SHOW: "DEPOT_SHOW",
    DEPOT_EDIT: "DEPOT_EDIT",
    ACCOUNT_SHOW: "ACCOUNT_SHOW",
    ACCOUNT_EDIT: "ACCOUNT_EDIT",
    PAYMENT_SHOW: "PAYMENT_SHOW",
    PAYMENT_EDIT: "PAYMENT_EDIT",
    INVOICE_SHOW: "INVOICE_SHOW",
    INVOICE_EDIT: "INVOICE_EDIT",
    CASH_DESK_SHOW: "CASH_DESK_SHOW",
    CASH_DESK_EDIT: "CASH_DESK_EDIT",
    CHEQUE_SHOW: "CHEQUE_SHOW:",
    CHEQUE_EDIT: "CHEQUE_EDIT",
  },
  PERMISSIONS: [
    { value: "PAYMENT_SHOW", label: "لیست پرداختی و دریافتی" },
    { value: "PAYMENT_EDIT", label: "ویرایش پرداختی و دریافتی " },
    { value: "INVOICE_SHOW", label: "لیست فاکتور ها" },
    { value: "INVOICE_EDIT", label: "ویرایش فاکتور ها" },
    { value: "CASH_DESK_SHOW", label: "لیست صندوق ها" },
    { value: "CASH_DESK_EDIT", label: "ویرایش صندوق ها" },
    { value: "CHEQUE_SHOW", label: "لیست چک ها" },
    { value: "CHEQUE_EDIT", label: "ویرایش چک ها" },
    { value: "USER_SHOW", label: "لیست کاربران" },
    { value: "USER_EDIT", label: "ویرایش کاربران" },
    { value: "PRODCUT_SHOW", label: "لیست محصولات" },
    { value: "PRODCUT_EDIT", label: "ویرایش محصولات" },
    { value: "CUSTOMER_SHOW", label: "لیست مشتریان" },
    { value: "CUSTOMER_EDIT", label: "ویرایش مشتریان" },
    { value: "DRIVER_SHOW", label: "لیست رانندگان" },
    { value: "DRIVER_EDIT", label: "ویرایش رانندگان" },
    { value: "DEPOT_SHOW", label: "لیست انبارها" },
    { value: "DEPOT_EDIT", label: "ویرایش انبارها" },
    { value: "ACCOUNT_SHOW", label: "لیست حساب ها" },
    { value: "ACCOUNT_EDIT", label: "ویرایش حساب ها" },
  ],
  BANK_TRANSACTION_TYPE: [
    { value: "کارت به کارت", label: "کارت به کارت" },
    { value: "دستگاه پوز", label: "دستگاه پوز" },
    { value: "پایا/ساتنا", label: "پایا/ساتنا" },
    { value: "واریز به/از حساب", label: "واریز به/از حساب" },
  ],
};
export default Constant;
